import React, { useState } from 'react';
import { AIAction } from '../types';
import {
  Zap,
  CheckCircle2,
  XCircle,
  Sliders,
  Clock,
  ShieldCheck,
  TrendingDown,
  Sparkles,
  ArrowRight,
  History
} from 'lucide-react';

interface AIActionsViewProps {
  actions: AIAction[];
  onApproveAction: (id: string) => void;
  onDismissAction: (id: string) => void;
  onSimulateAction?: (action: AIAction) => void;
}

export const AIActionsView: React.FC<AIActionsViewProps> = ({
  actions,
  onApproveAction,
  onDismissAction,
  onSimulateAction
}) => {
  const [filter, setFilter] = useState<'all' | 'pending' | 'approved'>('all');

  const pendingActions = actions.filter(a => a.status === 'pending');
  const approvedActions = actions.filter(a => a.status === 'approved');

  const getRiskBadge = (risk: AIAction['riskLevel']) => {
    switch (risk) {
      case 'critical':
        return 'bg-[#221111] text-[#CC3333] border border-[#CC3333]/40';
      case 'elevated':
        return 'bg-[#221A11] text-[#FF8800] border border-[#FF8800]/40';
      case 'watch':
      default:
        return 'bg-[#141414] text-[#888888] border border-[#1F1F1F]';
    }
  };

  return (
    <div id="ai-action-center-page" className="space-y-6">
      {/* Header */}
      <div className="p-4 sm:p-5 rounded bg-[#0A0A0A] border border-[#1F1F1F] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <Zap className="w-4 h-4 text-[#F27D26]" />
            <h2 className="text-xs sm:text-sm font-semibold text-white tracking-wide uppercase">
              AI ACTION CENTER &bull; AUTONOMOUS DISRUPTION MITIGATION
            </h2>
          </div>
          <p className="text-[11px] text-[#666666] mt-0.5 font-mono">
            Prescriptive mitigation protocols generated by REPLENOVA Risk & Sourcing Engine.
          </p>
        </div>

        <div className="flex items-center gap-1 bg-[#050505] p-1 rounded border border-[#1F1F1F] font-mono text-[10px]">
          {(['all', 'pending', 'approved'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-3 py-1 rounded transition-colors cursor-pointer capitalize font-medium ${
                filter === tab
                  ? 'bg-[#1A1A1A] text-white border border-[#2A2A2A]'
                  : 'text-[#888888] hover:text-white border border-transparent'
              }`}
            >
              {tab} {tab === 'pending' ? `(${pendingActions.length})` : tab === 'approved' ? `(${approvedActions.length})` : `(${actions.length})`}
            </button>
          ))}
        </div>
      </div>

      {/* Pending Actions List */}
      {(filter === 'all' || filter === 'pending') && pendingActions.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-xs font-mono font-bold text-[#888888] uppercase tracking-wider flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#CC3333] animate-pulse" />
            ACTION DISPATCH QUEUE ({pendingActions.length} READY FOR AUTHORIZATION)
          </h3>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {pendingActions.map((action) => (
              <div
                key={action.id}
                className="p-4 sm:p-5 rounded bg-[#0A0A0A] border border-[#1F1F1F] hover:border-[#2A2A2A] transition-colors flex flex-col justify-between space-y-4"
              >
                <div>
                  <div className="flex items-center justify-between gap-2 mb-2 pb-2 border-b border-[#141414]">
                    <div className="flex items-center gap-2">
                      <span
                        className={`font-mono text-[9px] uppercase px-1.5 py-0.5 rounded font-bold ${getRiskBadge(
                          action.riskLevel
                        )}`}
                      >
                        {action.riskLevel}
                      </span>
                      <span className="font-mono text-[10px] text-[#666666]">
                        {action.category} &bull; {action.timestamp}
                      </span>
                    </div>

                    <span className="font-mono text-[10px] text-white bg-[#141414] px-2 py-0.5 rounded border border-[#1F1F1F]">
                      {action.confidencePct}% Confidence
                    </span>
                  </div>

                  <h4 className="text-xs font-semibold text-white leading-snug">
                    {action.title}
                  </h4>

                  <p className="text-[11px] text-[#888888] mt-1.5 leading-relaxed">
                    <strong className="text-[#AAAAAA]">Trigger:</strong> {action.problem}
                  </p>

                  <div className="mt-3 p-3 rounded bg-[#0D0D0D] border border-[#1F1F1F] space-y-1">
                    <span className="text-[10px] font-mono text-[#F27D26] font-bold block uppercase tracking-wider">
                      Recommended Action:
                    </span>
                    <p className="text-xs text-[#D1D1D1] font-medium leading-relaxed">
                      {action.recommendedAction}
                    </p>
                  </div>
                </div>

                <div>
                  {/* Metrics Row */}
                  <div className="grid grid-cols-2 gap-2 p-2.5 rounded bg-[#0D0D0D] border border-[#141414] font-mono text-xs mb-3">
                    <div>
                      <span className="text-[#666666] block text-[10px]">ESTIMATED COST</span>
                      <span className="text-[#FF8800] font-bold">₹{action.costInr.toLocaleString()}</span>
                    </div>
                    <div>
                      <span className="text-[#666666] block text-[10px]">RISK REDUCTION</span>
                      <span className="text-green-500 font-bold">-{action.riskReductionPct}%</span>
                    </div>
                  </div>

                  {/* Action Buttons: APPROVE, SIMULATE, DISMISS */}
                  <div className="flex items-center justify-end gap-2 font-mono text-xs">
                    <button
                      onClick={() => onDismissAction(action.id)}
                      className="px-3 py-1.5 rounded bg-[#141414] hover:bg-[#1F1F1F] text-[#888888] hover:text-white border border-[#1F1F1F] cursor-pointer transition-colors"
                    >
                      DISMISS
                    </button>
                    {onSimulateAction && (
                      <button
                        onClick={() => onSimulateAction(action)}
                        className="px-3 py-1.5 rounded bg-[#1A1A1A] hover:bg-[#222222] text-[#F27D26] border border-[#F27D26]/30 cursor-pointer flex items-center gap-1 transition-colors"
                      >
                        <Sliders className="w-3 h-3" />
                        <span>SIMULATE</span>
                      </button>
                    )}
                    <button
                      onClick={() => onApproveAction(action.id)}
                      className="px-4 py-1.5 rounded bg-[#F27D26] hover:bg-[#FF8800] text-black font-bold cursor-pointer uppercase tracking-wider flex items-center gap-1 transition-colors shadow-md"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5 fill-current text-black" />
                      <span>APPROVE</span>
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Activity Timeline Section (Approved & Executed Actions) */}
      {(filter === 'all' || filter === 'approved') && (
        <div className="space-y-3 pt-4 border-t border-[#1F1F1F]">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-mono font-bold text-[#888888] uppercase tracking-wider flex items-center gap-2">
              <History className="w-4 h-4 text-green-500" />
              APPROVED ACTIONS EXECUTION TIMELINE
            </h3>
            <span className="text-xs font-mono text-green-500">
              {approvedActions.length} Actions Active in ERP
            </span>
          </div>

          <div className="space-y-2.5">
            {approvedActions.map((action) => (
              <div
                key={action.id}
                className="p-3.5 rounded bg-[#0A0A0A] border border-[#1F1F1F] flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs"
              >
                <div className="flex items-start gap-3">
                  <div className="p-1.5 rounded bg-[#141F14] text-green-500 shrink-0 mt-0.5 border border-green-800/40">
                    <CheckCircle2 className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h5 className="font-semibold text-white">{action.title}</h5>
                      <span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-[#141F14] text-green-500 border border-green-800/40 font-bold">
                        EXECUTED &bull; ERP SYNCED
                      </span>
                    </div>
                    <p className="text-[#888888] text-[11px] mt-0.5 leading-relaxed">
                      {action.recommendedAction}
                    </p>
                  </div>
                </div>

                <div className="shrink-0 flex items-center gap-4 font-mono text-[11px] text-right">
                  <div>
                    <span className="text-[#666666] block text-[9px]">SURCHARGE</span>
                    <span className="text-[#D1D1D1]">₹{action.costInr.toLocaleString()}</span>
                  </div>
                  <div>
                    <span className="text-[#666666] block text-[9px]">RISK MITIGATED</span>
                    <span className="text-green-500 font-bold">-{action.riskReductionPct}%</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
